version: "3.7"

services:
  svc1:
    image: nginx:latest
    container_name: svc1
    hostname: svc1
    networks:
      - my_network
    command: /bin/bash -c "echo 'connected to svc1' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;' " 
  svc2:
    image: nginx:latest
    container_name: svc2
    hostname: svc2
    networks:
      - my_network
    command: /bin/bash -c "echo 'connected to svc2' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;' " 
   
   

networks:
  my_network:
    driver: bridge





   
